spring:
  application:
    name: scgw
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: user
        uri: lb://user-service
        order: 0
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

server:
  port: 9090

management:
  server:
    port: 29090
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
      base-path: /healthcheck

logging:
  config: classpath:log4j2.xml


ribbon:
  connectTimeout: 2000
  readTimeout: 6000
  serverListRefreshInterval: 5000


